#!/bin/bash
# Pull from host

. /srv/dcp/bin/dcp2_common

usage()
{
    cat <<EOF
    usage: $1 [-m <message>] [-f] (-h <hosts_list> | <host> ) [<files>]
       Commit files in the sparse tree to the store
       -i  Commit the "installed package" manifest (only needed if
           specific files listed otherwise it's committed anyway)
       -m  A message to apply to every commit message
       -a  All hosts
       -h  <hosts_list> is a file containing list of hosts to push to
       <files> specified manually will be suject to a 'git add' and
              'git commit' if needed. Note that these files may be given
              an absolute path or a path relative to / on the remote host.
EOF
    return 0
}

edit_git_msg="-e"
while getopts "arpim:fh:" opt; do
    case $opt in
	a ) host_list=$(cd $HOST_STORE; find * -maxdepth 0  -type d);;
	i ) manifest=1;;
	m ) message=$OPTARG; edit_git_msg="";;
	h ) host_list=$(cat $OPTARG);;
	\? ) usage
            exit 1;;
	: ) echo "Option -$OPTARG requires an argument." >&2
	    usage
	    exit 1;;
	* ) usage
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

# There must be a host
if [[ $# -eq 0 && -z "$host_list" ]]; then
    echo "No <host> provided"
    usage
    exit 1
fi

commit_ () {
    host=$1
    shift

#    if ! ping -c1 $host >/dev/null 2>&1 ; then
#	echo $host not available
#	return
#    fi

    cd ${HOST_STORE}/$host

    echo "$message" > /tmp/dcpmsg$$

    # Add manifest to git or if nothing specified then commit everything (including manifest)
    if [[ $manifest == 1 || $# -eq 0 ]]; then
	git add manifest
	cat <<EOF >> /tmp/dcpmsg$$
$host : Installed package manifest updated
EOF
    fi

    if [[ $manifest != 1 ]]; then
	echo "manifest not 1 it's $manifest"
        # Add sparse files to git
	if [[ $# -eq 0 ]]; then
	    git add --all sparse
	    cat <<EOF >> /tmp/dcpmsg$$
$host : All files updated from the remote host
EOF
	else
	    # dcp2_commit host /etc/fstab /etc/ldap.conf
	    # should do a : git add etc/fstab etc/ldap.conf
	    cd sparse
	    for file in "$@"; do
                # Only commit existing files
		[[ -e $file ]] && files="$files $(echo $file | sed -e s'-^/--')"
	    done
	    git add --all $files
	    cat <<EOF >> /tmp/dcpmsg$$
$host : Some files updated from the remote host:
$files
EOF
	    cd ..
	fi
    fi
    git commit -F /tmp/dcpmsg$$ $edit_git_msg
}

# Which hosts get a commit
if [[ -n $host_list ]]; then
    for host in $host_list; do
	commit_ $host "$@"
    done
else
    commit_ "$@"
fi
