#!/bin/bash
# Status check

. /srv/dcp/bin/dcp_common

usage()
{
    cat <<EOF
    usage: $1 [-v] [<hosts>]
       Changelog of hosts. Default to all hosts
EOF
    return 0
}

while getopts ":v" opt; do
    case $opt in
#	v ) verbose=1;;
	\? ) usage
            exit 1;;
	* ) usage
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

log_ () {
    host=$1

    cd ${HOST_STORE}/$host
    echo "$host"
    echo "git log :"
    git log
    echo
}


# Which hosts need a log ?
if [ $# -eq 0 ]; then
    hosts=$(cd $HOST_STORE; find * -maxdepth 0  -type d)
else
    hosts="$@"
fi

for h in $hosts; do
    log_ $h
done
