#!/bin/bash

. /srv/dcp/bin/dcp_common

usage()
{
    cat <<EOF
    $1 
       Create the site area
EOF
    return 0
}

if [ $# -ne 0 ]; then
        usage $(basename $0)
        exit 1
fi

mkdir -p ${HOST_STORE}
chown root:root ${HOST_STORE}
chmod 700 ${HOST_STORE}

mkdir -p ${SITE_STORE}
chown root:root ${SITE_STORE}
chmod 700 ${SITE_STORE}

if [ -e ${SITE_STORE}/.git ]; then
   echo "There is an existing site store"
   exit 1
fi

# This creates a git repo for the site
git init ${SITE_STORE}
(
    cd ${SITE_STORE}
)

