#!/bin/bash
# Pull from host

. /srv/dcp/bin/dcp_common

usage()
{
    cat <<EOF
    usage: $1 [-i] [-p] [-m <message>] (-a | -h <hosts_list> | <host> ) [<files>]
       Commit files in the sparse tree to the store
       -i  Commit the "installed package" manifest (only needed if
           specific files listed otherwise it's committed anyway)
       -p  Do a simple dcp_pull before the commit
       -m  A message to apply to every commit message
       -a  All hosts
       -h  <hosts_list> is a file containing list of hosts to push to
       <files> specified manually will be suject to a 'git add' and
              'git commit' if needed. Note that these files may be given
              an absolute path or a path relative to / on the remote host.
EOF
    return 0
}

edit_git_msg="-e"
while getopts "ipm:ah:" opt; do
    case $opt in
	i ) manifest=1;;
        p ) pull=1;;
	m ) message=$OPTARG; edit_git_msg="";;
	a ) host_list=$(all_hosts_);;
	h ) host_list=$(cat $OPTARG);;
	\? ) usage
            exit 1;;
	: ) echo "Option -$OPTARG requires an argument." >&2
	    usage
	    exit 1;;
	* ) usage
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

# There must be a host
if [[ $# -eq 0 && -z "$host_list" ]]; then
    echo "No <host> provided"
    usage
    exit 1
fi

commit_ () {
    host=$1
    shift

#    if ! ping -c1 $host >/dev/null 2>&1 ; then
#	echo $host not available
#	return
#    fi

    cd ${HOST_STORE}/$host || {
	echo "No such host : $host .... should you run dcp_add_host"
	return
    }

    msgfile=$(mktemp)
    echo "$message" > ${msgfile}

    # Add manifest to git or if nothing specified then commit everything (including manifest)
    if [[ $manifest == 1 || $# -eq 0 ]]; then
	git add manifest
	cat <<EOF >> ${msgfile}
$host : Installed package manifest updated
EOF
    fi

    if [[ $manifest != 1 ]]; then
        # Add sparse files to git
	if [[ $# -eq 0 ]]; then
	    git add --all sparse
	    cat <<EOF >> ${msgfile}
$host : All files updated from the remote host
EOF
	else
	    # dcp_commit host /etc/fstab /etc/ldap.conf
	    # should do a : git add etc/fstab etc/ldap.conf
	    cd sparse
	    for file in "$@"; do
                # Only commit existing files
		[[ -e $file ]] && files="$files $(echo $file | sed -e s'-^/--')"
	    done
	    git add --all $files
	    cat <<EOF >> ${msgfile}
$host : Some files updated from the remote host:
$files
EOF
	    cd ..
	fi
    fi
    # Commit the changes and allow msg to be edited if -m not used
    git commit -F ${msgfile} $edit_git_msg

    rm ${msgfile}
}

# Which hosts get a commit
if [[ -n $host_list ]]; then
    for host in $host_list; do
        [[ -n $pull ]] && dcp_pull $host
	commit_ $host "$@"
    done
else
    [[ -n $pull ]] && dcp_pull $1
    commit_ "$@"
fi
