#!/bin/bash
# History

. /srv/dcp/bin/dcp_common

usage()
{
    cat <<EOF
    usage: $1 [-f] [-s <date>] [-a | <hosts>]
    or:    $1 [-c <commit>] <host>
       Changelog of hosts. Default to all hosts
       [-f]  pass --name-only to git log (list files)
       [-s]  since <date> : note uses git's flexible format so
             -s "yesterday" or 
             -s "2 days ago"
       [-c]  show the details of a particular commit
EOF
    return 0
}

while getopts "fs:c:a" opt; do
    case $opt in
	f ) g_opts="$g_opts --name-only";;
	s ) g_opts="$g_opts --since=\"$OPTARG\"";;
	c ) commit=$OPTARG;;
	a ) host_list=$(all_hosts_);;
	\? ) usage
            exit 1;;
	* ) usage
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

show_commit_ () {
    host=$1

    cd ${HOST_STORE}/$host

    git show --pretty $commit

}

log_ () {
    host=$1

    cd ${HOST_STORE}/$host
    tmp_log=$(mktemp)
    # Use eval since variable expansion needs re-parsing
    eval git log $g_opts > $tmp_log
    if [ -s $tmp_log ] ; then
	echo Log for $host
	cat $tmp_log
	echo
    fi
    rm -f $tmp_log
}

# Which hosts need a log ?
if [[ $# -eq 0 ]]; then
    if [[ $host_list == "" ]]; then
	echo "No '-a' or hosts specified ($host_list)"
	usage
	exit 1
    fi
else
    host_list="$@"
fi

for h in $host_list; do
    if [[ -n $commit ]]; then
	show_commit_ $h
    else
	log_ $h
    fi
done
