#!/bin/bash
# Status check

. /srv/dcp/bin/dcp_common

usage()
{
    cat <<EOF
    usage: $1 [-v] [<hosts>]
       Check status of hosts. Default to all hosts
       -v  Also show a git diff
EOF
    return 0
}

while getopts ":v" opt; do
    case $opt in
	v ) verbose=1;;
	\? ) usage
            exit 1;;
	* ) usage
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

status_ () {
    host=$1

    cd ${HOST_STORE}/$host
    echo "$host"
    echo "git status :"
    git status --short
    echo
    if [[ -n "$verbose" ]]; then
	echo "git diff :"
	git diff
	echo
    fi
    echo "files to update :"
    if ping -c1 $host >/dev/null 2>&1 ; then
        # get the filelist
	find . -name .git -prune -o -type f -print > ../${host}.files
	rsync -a --dry-run --itemize-changes --files-from=../${host}.files root@$host:/ . 2>/dev/null
	# If there is a remote change we could:
	# git stash... pull... diff... reset, restore stash
#	git stash
#	rsync -a -v --itemize-changes --files-from=../${host}.files root@$host:/ .
	# Check remote pending
	echo pending files:
	ssh $host cat /var/dcp/register 2\>/dev/null
    else
	echo "($host unreachable)"
    fi
    echo
}


# Which hosts need a status report ?
if [ $# -eq 0 ]; then
    hosts=$(cd $HOST_STORE; find * -maxdepth 0  -type d)
else
    hosts="$@"
fi

for h in $hosts; do
    status_ $h
done
