#!/bin/bash
# Status check

. /srv/dcp/bin/dcp_common

usage()
{
    cat <<EOF
    usage: $1 [-v] [-l] [<hosts>]
       Check status of hosts. Default to all hosts
       -v  Also show a git diff
       -l  Show current list of managed files instead of checking status of them
       -q  Silent unless something to report.
EOF
    return 0
}

noisy=1
while getopts "vlq" opt; do
    case $opt in
	v ) verbose=1;;
	q ) noisy="";;
	l ) list_files=1;;
	\? ) usage
            exit 1;;
	* ) usage
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

status_ () {
    host=$1

    activity=""

    # First get all the status info
    cd ${HOST_STORE}/$host
    git_status=$(git status --short)
    if [[ -n "$verbose" ]]; then
	git_diff=$(git diff)
    fi
    if ping -c1 $host >/dev/null 2>&1 ; then
        # get the filelist, ignoring the git repo and the metatadata
	find . -name .git -prune -o \( \! -name .metadata \! -name .gitignore \! -name . \) \( -type f -o -type l -o -type d \) -print > ../${host}.files
	# Now get a list of changed files
	rsync_files=$(rsync -e 'ssh -x' -a -x --dry-run --itemize-changes --exclude ./  --files-from=../${host}.files root@$host:/ . )
	# If there is a remote change we could:
	# git stash... pull... diff... reset, restore stash
#	git stash
#	rsync -a -v --itemize-changes --files-from=../${host}.files root@$host:/ .
	# Check remote pending
	pending_files=$(ssh -x $host cat /var/dcp/register 2\>/dev/null)
        # Get an updated manifest from the host
	ssh -x $host dpkg-query -W 2\>/dev/null > ../${host}.manifest.pending
	manifest_diff=$(diff --unchanged-line-format="" --old-line-format="removed  : %L" --new-line-format="installed: %L" -N ../${host}.manifest ../${host}.manifest.pending)
#	rm -f ../${host}.manifest.pending
    else
	rsync_files="(No rsync data: $host unreachable)"
	pending_files="(No rsync data: $host unreachable)"
    fi
    metastore_compare=$(metastore --compare)

    if [[ ! -z "$git_status$metastore_compare$rsync_files$pending_files$manifest_diff" ]]; then
	activity=1
    fi

    [[ ! -z "$activity$noisy" ]] && echo "$host"
    if [[ ! -z "$git_status" ]]; then
	echo "Files not in sync with local git :"
	echo "$git_status"
	echo
	if [[ -n "$verbose" ]]; then
	    echo "git diff :"
	    echo "$git_diff"
	    echo
	fi
    fi
    if [[ ! -z "$metastore_compare" ]]; then
	echo "Files with attribute changes compared to local git :"
	echo "$metastore_compare"
    fi
    if [[ ! -z "$rsync_files" ]]; then
	echo "Files not in sync with remote host :"
	echo "$rsync_files"
    fi
    if [[ ! -z "$pending_files" ]]; then
	echo "Files awaiting pull from remote host :"
	echo "$pending_files"
    fi
    if [[ ! -z "$manifest_diff" ]]; then
	echo "Installed package changes :"
	echo "$manifest_diff"
    fi
    [[ -z "$activity$noisy" ]] && echo "No changes"
}


# Which hosts need a status report ?
if [ $# -eq 0 ]; then
    hosts=$(cd $HOST_STORE; find * -maxdepth 0  -type d)
else
    hosts="$@"
fi

    
for h in $hosts; do
    if [[ ! -z "$list_files" ]]; then
	echo "Files managed for $h :"
	sed 's@^./@/@' ${HOST_STORE}/${h}.files
    else
	status_ $h
    fi
done
